export const SOUND_TRACKS = [
  {
    id: "funk_smooth_party",
    title: "Funk Smooth Party",
    genre: "Nu-Funk / Retro",
    bpm: "124 BPM",
    vibe: "Upbeat 1970s funk groove with brass hits and dynamic breaks",
    assetPath: "/assets/audio/funk_smooth_party.mp3",
    durationSeconds: 71.5,
    fileName: "funk_smooth_party.mp3",
  },
  {
    id: "urban_boom_bap",
    title: "Urban Boom Bap",
    genre: "Hip-Hop / Rap",
    bpm: "92 BPM",
    vibe: "Punchy 46-second classic boom-bap rhythm with crisp snare snaps",
    assetPath: "/assets/audio/urban_boom_bap.mp3",
    durationSeconds: 46.0,
    fileName: "urban_boom_bap.mp3",
  },
  {
    id: "rap_beat_extended",
    title: "Urban Boom Bap (66s)",
    genre: "Hip-Hop / Rap",
    bpm: "92 BPM",
    vibe: "Extended 66-second boom-bap rhythm with heavy kick & hi-hat chops",
    assetPath: "/assets/audio/rap_beat_extended.mp3",
    durationSeconds: 66.4,
    fileName: "rap_beat_extended.mp3",
  },
  {
    id: "hood_90s_boombap",
    title: "90s Hood Boom Bap",
    genre: "Golden Era / 90s",
    bpm: "90 BPM",
    vibe: "Authentic 90s vinyl texture with vintage drum chops and street warmth",
    assetPath: "/assets/audio/hood_90s_boombap.mp3",
    durationSeconds: 174.0,
    fileName: "hood_90s_boombap.mp3",
  },
  {
    id: "voicemails_90s_boombap",
    title: "90s Voicemails",
    genre: "Lo-Fi / 90s",
    bpm: "88 BPM",
    vibe: "Nostalgic telephone intro leading into a laidback dusty boom-bap beat",
    assetPath: "/assets/audio/voicemails_90s_boombap.mp3",
    durationSeconds: 176.1,
    fileName: "voicemails_90s_boombap.mp3",
  },
  {
    id: "sweet_life_chill",
    title: "Sweet Life Lounge",
    genre: "Downtempo / Chill",
    bpm: "85 BPM",
    vibe: "Deep synth basslines and stylish luxury lounge sunset vibes",
    assetPath: "/assets/audio/sweet_life_chill.mp3",
    durationSeconds: 102.3,
    fileName: "sweet_life_chill.mp3",
  },
  {
    id: "lofi_sunset_beat",
    title: "Lo-Fi Sunset Beat",
    genre: "Lo-Fi / Study",
    bpm: "80 BPM",
    vibe: "Warm vinyl crackle, gentle electric piano chords, and soothing tempo",
    assetPath: "/assets/audio/lofi_sunset_beat.mp3",
    durationSeconds: 113.5,
    fileName: "lofi_sunset_beat.mp3",
  },
  {
    id: "chill_vlog_beat",
    title: "Chill Vlog Hip-Hop",
    genre: "Lo-Fi / Vlog",
    bpm: "90 BPM",
    vibe: "Mellow electric keys and relaxing sunny beats for aesthetic reels",
    assetPath: "/assets/audio/chill_vlog_beat.mp3",
    durationSeconds: 96.0,
    fileName: "chill_vlog_beat.mp3",
  },
  {
    id: "percussion_drive",
    title: "Percussion Drive",
    genre: "Acoustic / Stomp",
    bpm: "115 BPM",
    vibe: "Organic stomps, handclaps, and rhythmic cajon builds",
    assetPath: "/assets/audio/percussion_drive.mp3",
    durationSeconds: 76.0,
    fileName: "percussion_drive.mp3",
  },
  {
    id: "action_stinger",
    title: "Action Stinger",
    genre: "Dynamic / Short",
    bpm: "130 BPM",
    vibe: "Fast-paced hype track tailor-made for rapid beat transitions",
    assetPath: "/assets/audio/action_stinger.mp3",
    durationSeconds: 44.9,
    fileName: "action_stinger.mp3",
  },
  {
    id: "celebration_anthem",
    title: "Celebration Anthem",
    genre: "Festive / Pop",
    bpm: "120 BPM",
    vibe: "Joyful celebration fanfare and driving rhythm for party reels",
    assetPath: "/assets/audio/celebration_anthem.mp3",
    durationSeconds: 130.9,
    fileName: "celebration_anthem.mp3",
  },
  {
    id: "heavy_bass_dubstep",
    title: "Heavy Bass Dubstep",
    genre: "Bass / Dubstep",
    bpm: "140 BPM",
    vibe: "High-energy electronic drop with heavy sub-bass wobble",
    assetPath: "/assets/audio/heavy_bass_dubstep.mp3",
    durationSeconds: 156.0,
    fileName: "heavy_bass_dubstep.mp3",
  },
  {
    id: "melodic_techno_journey",
    title: "Melodic Techno Journey",
    genre: "Techno / Deep",
    bpm: "126 BPM",
    vibe: "Hypnotic rolling bassline and cinematic synth progressions",
    assetPath: "/assets/audio/melodic_techno_journey.mp3",
    durationSeconds: 304.0,
    fileName: "melodic_techno_journey.mp3",
  },
  {
    id: "melody_so_melody",
    title: "Melody So Melody",
    genre: "House / Dance",
    bpm: "122 BPM",
    vibe: "Catchy progressive dance groove with sparkling vocal hooks",
    assetPath: "/assets/audio/melody_so_melody.mp3",
    durationSeconds: 166.6,
    fileName: "melody_so_melody.mp3",
  },
  {
    id: "aerobic_edm_remix",
    title: "Aerobic EDM Remix",
    genre: "EDM / Workout",
    bpm: "97 BPM",
    vibe: "Driving electronic beat, high motivation drop, and club energy",
    assetPath: "/assets/audio/aerobic_edm_remix.mp3",
    durationSeconds: 156.9,
    fileName: "aerobic_edm_remix.mp3",
  },
  {
    id: "emotional_happy_boombap",
    title: "Goodbye Emotional Beat",
    genre: "Emotional / Hip-Hop",
    bpm: "88 BPM",
    vibe: "Soulful piano chords, warm vinyl snare, and heartfelt storytelling rhythm",
    assetPath: "/assets/audio/emotional_happy_boombap.mp3",
    durationSeconds: 243.6,
    fileName: "emotional_happy_boombap.mp3",
  },
  {
    id: "little_do_you_know",
    title: "Little Do You Know",
    genre: "Cinematic / Emotional",
    bpm: "74 BPM",
    vibe: "Atmospheric piano chords and emotive slow-burn rhythm for storytelling",
    assetPath: "/assets/audio/little_do_you_know.mp3",
    durationSeconds: 154.0,
    fileName: "little_do_you_know.mp3",
  },
];

export const SAMPLE_PHOTOS = [
  "/assets/sample_photos/sample_01.jpg",
  "/assets/sample_photos/sample_02.jpg",
  "/assets/sample_photos/sample_03.jpg",
  "/assets/sample_photos/sample_04.jpg",
  "/assets/sample_photos/sample_05.jpg",
  "/assets/sample_photos/sample_06.jpg",
  "/assets/sample_photos/sample_07.jpg",
  "/assets/sample_photos/sample_08.jpg",
];

export const TEMPLATES = [
  { id: "pendulum", name: "Pendulum", subtitle: "Swinging cuts with mirrored borders", emoji: "🪞", isPro: false },
  { id: "beat-cut", name: "Beat Cut", subtitle: "Classic snappy beat drop transitions", emoji: "⚡", isPro: false },
  { id: "beat-bounce", name: "Bounce", subtitle: "Kinetic bassline scale bounces", emoji: "🏀", isPro: false },
  { id: "cinematic-zoom", name: "Cinematic Zoom", subtitle: "Dynamic optical punch-in zooms", emoji: "🎬", isPro: false },
  { id: "beat-fade", name: "Fade", subtitle: "Silky crossfades for ambient beats", emoji: "🌊", isPro: false },
  { id: "glide-pan", name: "Glide", subtitle: "Lateral gliding pan motion", emoji: "🛹", isPro: false },
  { id: "beat-pulse", name: "Pulse", subtitle: "Pulsing emotional sub-bass pump", emoji: "💓", isPro: false },
  { id: "punch-cut", name: "Punch", subtitle: "High-impact rhythmic punch cuts", emoji: "🥊", isPro: false },
  { id: "reveal-tiles", name: "Reveal Boxes", subtitle: "Geometric box tile mosaic reveals", emoji: "🔲", isPro: false },
  { id: "beat-slide", name: "Slide", subtitle: "Directional kinetic slide transitions", emoji: "➡️", isPro: false },
  { id: "slow-drift", name: "Slow Drift", subtitle: "Atmospheric slow cinematic drift", emoji: "☁️", isPro: false },
  { id: "sway-ballad", name: "Sway", subtitle: "Gentle rhythmic swaying cadence", emoji: "🍃", isPro: false },
  { id: "beat-whip", name: "Whip", subtitle: "High-velocity directional whip pans", emoji: "🌪️", isPro: false },
  { id: "zoom-out-reveal", name: "Zoom Out", subtitle: "Expanding optical reveal zoom", emoji: "🔍", isPro: false },
];

export const PRICING_PLANS = [
  {
    id: "weekly",
    name: "Weekly Pass",
    price: 149,
    period: "week",
    durationDays: 7,
    description: "Great for weekend creators & one-off events",
    badge: null,
    features: [
      "8 Credits / week included",
      "Unlimited 1080p Master Renders",
      "No Watermark on any export",
      "All 14 Pro Templates unlocked",
      "Custom Title Card branding",
      "7 Days Full Access",
    ],
  },
  {
    id: "monthly",
    name: "Monthly Pro",
    price: 349,
    period: "month",
    durationDays: 30,
    description: "Our most popular plan for active creators",
    badge: "MOST POPULAR",
    features: [
      "40 Credits / month included",
      "Unlimited 1080p Master Renders",
      "No Watermark on any export",
      "All 14 Pro Templates unlocked",
      "Priority Queue slot allocation",
      "Custom Fonts & Border styling",
      "30 Days Full Access",
    ],
  },
  {
    id: "annual",
    name: "Annual Studio",
    price: 1799,
    period: "year",
    durationDays: 365,
    description: "Best value for agencies & power creators",
    badge: "SAVE 57%",
    features: [
      "36 Credits / month included",
      "Everything in Monthly Pro",
      "VIP Early Access to Video Renders",
      "Highest Queue Priority",
      "Full Commercial Use License",
      "365 Days Full Access",
    ],
  },
];

export const TOP_UPS = [
  { id: "T1", credits: 5, price: 39 },
  { id: "T2", credits: 10, price: 69 },
  { id: "T3", credits: 25, price: 149 },
  { id: "T4", credits: 50, price: 269 },
  { id: "T5", credits: 100, price: 469 },
  { id: "T6", credits: 250, price: 999 },
];

export const ASPECT_RATIOS = [
  { id: "9:16", label: "9:16 Reel / Story", frameValue: "portrait", icon: "📱" },
  { id: "1:1", label: "1:1 Square Post", frameValue: "square", icon: "⏹️" },
  { id: "16:9", label: "16:9 Landscape Video", frameValue: "landscape", icon: "🖥️" },
];

export const TITLE_FONTS = [
  { id: "great_vibes", label: "Great Vibes (Cursive)" },
  { id: "cinzel", label: "Cinzel (Cinematic Serif)" },
  { id: "montserrat", label: "Montserrat (Modern Bold)" },
  { id: "bebas_neue", label: "Bebas Neue (Impact Headline)" },
  { id: "playfair", label: "Playfair Display (Luxury)" },
];

export const DEFAULT_SERVER_URL = "";
