plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.kiro.snapbeat'
    compileSdk 34

    defaultConfig {
        applicationId "com.kiro.snapbeat"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "SERVER_URL", '"http://192.168.68.104:8772"'
    }
    
    buildFeatures {
        viewBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Networking
            implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}
